from __future__ import annotations

from html import escape
from io import BytesIO
from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from reportlab.graphics.shapes import Drawing, Line, Rect, String
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import landscape, letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


NAVY=colors.HexColor("#0B2039"); BLUE=colors.HexColor("#0877C9"); GREEN=colors.HexColor("#0C9A70")
RED=colors.HexColor("#CC4056"); ORANGE=colors.HexColor("#EE8A1C"); MUTED=colors.HexColor("#657689")
LIGHT=colors.HexColor("#F3F6F9"); LINE=colors.HexColor("#DCE4EC")

TEXT={
    "en":{
        "title":"Quotation follow-up report","special_title":"Special quotation follow-up report","period":"Period",
        "agent":"Agent","generated_by":"Generated by","scope":"Scope","my":"My activity","team":"All team",
        "summary":"Period summary","added":"Quotations added","reviewed":"Quotations reviewed",
        "status":"Status changes","po":"Converted to PO","financial":"Financial summary",
        "pending":"Pending quotation total","po_quoted":"Quoted value converted to PO","po_final":"Final PO total","variance":"Variance",
        "losses":"Lost quotations by reason","no_losses":"No quotations were marked Lost during this period.",
        "po_detail":"QT to PO conversions","no_po":"No quotations were converted to PO during this period.",
        "quotation":"Quotation","customer":"End User","po_date":"PO date","quoted":"Quoted total","final_po":"Final PO","invoice_count":"Invoices","reason":"Loss reason","date":"Date",
        "review_detail":"Reviewed quotations and saved activity","user":"User","activity":"Saved activity","net":"Net internal total",
    },
    "es":{
        "title":"Reporte de seguimiento de cotizaciones","special_title":"Reporte de seguimiento de cotizaciones especiales","period":"Periodo",
        "agent":"Agente","generated_by":"Generado por","scope":"Alcance","my":"Mi actividad","team":"Todo el equipo",
        "summary":"Resumen del periodo","added":"Cotizaciones agregadas","reviewed":"Cotizaciones revisadas",
        "status":"Cambios de estatus","po":"Convertidas a PO","financial":"Resumen financiero",
        "pending":"Total de cotizaciones pendientes","po_quoted":"Valor cotizado convertido a PO","po_final":"Total final de PO","variance":"Diferencia",
        "losses":"Cotizaciones perdidas por motivo","no_losses":"No se marcaron cotizaciones como perdidas durante este periodo.",
        "po_detail":"Conversiones de QT a PO","no_po":"No hubo conversiones a PO durante este periodo.",
        "quotation":"Cotización","customer":"Usuario final","po_date":"Fecha de PO","quoted":"Total cotizado","final_po":"PO final","invoice_count":"Facturas","reason":"Motivo de pérdida","date":"Fecha",
        "review_detail":"Cotizaciones revisadas y actividad guardada","user":"Usuario","activity":"Actividad guardada","net":"Total neto interno",
    },
}


def _money(value: object, currency: str) -> str:
    amount=float(value or 0)
    return f"JPY {amount:,.0f}" if currency=="JPY" else f"USD {amount:,.2f}"


def _styles() -> dict[str,ParagraphStyle]:
    base=getSampleStyleSheet()
    return {
        "title":ParagraphStyle("Title",parent=base["Title"],fontName="Helvetica-Bold",fontSize=19,leading=22,textColor=NAVY,alignment=TA_LEFT,spaceAfter=4),
        "subtitle":ParagraphStyle("Subtitle",parent=base["Normal"],fontSize=8.5,leading=12,textColor=MUTED),
        "section":ParagraphStyle("Section",parent=base["Heading2"],fontName="Helvetica-Bold",fontSize=12,leading=15,textColor=NAVY,spaceBefore=12,spaceAfter=7),
        "body":ParagraphStyle("Body",parent=base["BodyText"],fontSize=8,leading=11,textColor=NAVY),
        "small":ParagraphStyle("Small",parent=base["BodyText"],fontSize=7,leading=9,textColor=NAVY),
        "header":ParagraphStyle("Header",parent=base["BodyText"],fontName="Helvetica-Bold",fontSize=7,leading=9,textColor=colors.white),
        "kpi":ParagraphStyle("Kpi",parent=base["Normal"],fontName="Helvetica-Bold",fontSize=17,leading=19,textColor=NAVY,alignment=TA_CENTER),
        "label":ParagraphStyle("Label",parent=base["Normal"],fontName="Helvetica-Bold",fontSize=6.5,leading=8,textColor=MUTED,alignment=TA_CENTER),
    }


def _page(canvas, document) -> None:
    canvas.saveState(); width,height=landscape(letter); canvas.setFillColor(NAVY); canvas.rect(0,height-15,width,15,fill=1,stroke=0)
    canvas.setStrokeColor(LINE); canvas.line(document.leftMargin,22,width-document.rightMargin,22); canvas.setFont("Helvetica",7); canvas.setFillColor(MUTED)
    canvas.drawString(document.leftMargin,10,"NT TOOL - Sales follow-up"); canvas.drawRightString(width-document.rightMargin,10,f"Page {document.page}"); canvas.restoreState()


def _metric_table(items: list[tuple[Any,str]], styles: dict[str,ParagraphStyle]) -> Table:
    widths=[9.4*inch/len(items)]*len(items)
    table=Table([[Paragraph(str(v),styles["kpi"]) for v,_ in items],[Paragraph(label.upper(),styles["label"]) for _,label in items]],colWidths=widths,rowHeights=[.38*inch,.30*inch])
    table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),LIGHT),("BOX",(0,0),(-1,-1),.5,LINE),("INNERGRID",(0,0),(-1,-1),.5,colors.white),("VALIGN",(0,0),(-1,-1),"MIDDLE")]))
    return table


def _loss_chart(data: dict[str,Any], labels: dict[str,str]) -> Drawing:
    items=list(data.get("loss_breakdown",{}).items())
    drawing=Drawing(690,130); drawing.add(Line(28,25,675,25,strokeColor=LINE,strokeWidth=1))
    maximum=max([value for _,value in items] or [1]); width=max(34,min(80,560/max(1,len(items))))
    for index,(label,value) in enumerate(items[:8]):
        x=42+index*(width+20); height=72*value/maximum
        drawing.add(Rect(x,25,width,height,fillColor=RED,strokeColor=None,rx=3,ry=3)); drawing.add(String(x+width/2,31+height,str(value),textAnchor="middle",fontName="Helvetica-Bold",fontSize=8,fillColor=NAVY)); drawing.add(String(x+width/2,10,label[:18],textAnchor="middle",fontName="Helvetica",fontSize=6.5,fillColor=MUTED))
    if not items: drawing.add(String(345,65,labels["no_losses"],textAnchor="middle",fontName="Helvetica",fontSize=8,fillColor=MUTED))
    return drawing


def _po_chart(data: dict[str,Any]) -> Drawing:
    rows=list(data.get("po_rows",[]))[:8]; drawing=Drawing(690,150); drawing.add(Line(28,28,675,28,strokeColor=LINE,strokeWidth=1))
    maximum=max([max(float(r.get("quoted_total") or 0),float(r.get("po_total") or 0)) for r in rows] or [1])
    for index,row in enumerate(rows):
        x=43+index*80; qh=88*float(row.get("quoted_total") or 0)/maximum; ph=88*float(row.get("po_total") or 0)/maximum
        drawing.add(Rect(x,28,20,qh,fillColor=BLUE,strokeColor=None)); drawing.add(Rect(x+23,28,20,ph,fillColor=GREEN,strokeColor=None))
        drawing.add(String(x+22,12,str(row.get("folio") or "")[:12],textAnchor="middle",fontName="Helvetica",fontSize=6,fillColor=MUTED))
    drawing.add(String(610,135,"QT",fontName="Helvetica-Bold",fontSize=7,fillColor=BLUE)); drawing.add(String(640,135,"PO",fontName="Helvetica-Bold",fontSize=7,fillColor=GREEN))
    return drawing


def build_report_pdf(data: dict[str,Any], target: Path, language: str = "en") -> bytes:
    language=language if language in TEXT else "en"; labels=TEXT[language]; styles=_styles(); currency=data.get("currency","USD")
    target.parent.mkdir(parents=True,exist_ok=True); buffer=BytesIO(); document=SimpleDocTemplate(buffer,pagesize=landscape(letter),leftMargin=.45*inch,rightMargin=.45*inch,topMargin=.42*inch,bottomMargin=.42*inch,title=labels["title"],author="NT TOOL")
    title=labels["special_title"] if data.get("workspace")=="special" else labels["title"]
    agent=data.get("agent") or ("Todos" if language=="es" else "All agents"); generated=data.get("generated_by") or "—"; scope=labels["team"] if data.get("scope")=="all" else labels["my"]
    story=[Paragraph(title,styles["title"]),Paragraph(f"{labels['period']}: {escape(data['start_date'])} – {escape(data['end_date'])} &nbsp;&nbsp;|&nbsp;&nbsp; {labels['agent']}: {escape(str(agent))} &nbsp;&nbsp;|&nbsp;&nbsp; {labels['generated_by']}: {escape(str(generated))} &nbsp;&nbsp;|&nbsp;&nbsp; {labels['scope']}: {scope}",styles["subtitle"]),Spacer(1,12),Paragraph(labels["summary"],styles["section"]),
           _metric_table([(data["new_quotes"],labels["added"]),(data["quotes_reviewed"],labels["reviewed"]),(data["status_changes"],labels["status"]),(data["po_changes"],labels["po"])],styles),
           Paragraph(labels["financial"],styles["section"]),_metric_table([(_money(data["pending_value"],currency),labels["pending"]),(_money(data["po_quoted_value"],currency),labels["po_quoted"]),(_money(data["po_value"],currency),labels["po_final"]),(_money(float(data["po_value"])-float(data["po_quoted_value"]),currency),labels["variance"])],styles),
           Paragraph(labels["losses"],styles["section"]),_loss_chart(data,labels),Paragraph(labels["po_detail"],styles["section"]),_po_chart(data)]
    po_rows=data.get("po_rows",[])
    if po_rows:
        rows=[[Paragraph(labels[k],styles["header"]) for k in ("quotation","customer","po_date","invoice_count","quoted","final_po","variance")]]
        for row in po_rows: rows.append([Paragraph(escape(str(row.get("folio",""))),styles["small"]),Paragraph(escape(str(row.get("receptor",""))),styles["small"]),Paragraph(escape(str(row.get("po_date",""))),styles["small"]),Paragraph(escape(str(row.get("invoice_count",0))),styles["small"]),Paragraph(_money(row.get("quoted_total"),currency),styles["small"]),Paragraph(_money(row.get("po_total"),currency),styles["small"]),Paragraph(_money(row.get("variance"),currency),styles["small"])])
        story.append(_styled_table(rows,[1*inch,2.25*inch,.9*inch,.7*inch,1.3*inch,1.3*inch,1.3*inch]))
    else: story.append(Paragraph(labels["no_po"],styles["body"]))
    story.append(Paragraph(labels["losses"],styles["section"])); lost=data.get("lost_rows",[])
    if lost:
        rows=[[Paragraph(labels[k],styles["header"]) for k in ("quotation","customer","date","reason")]]
        for row in lost: rows.append([Paragraph(escape(str(row.get("folio",""))),styles["small"]),Paragraph(escape(str(row.get("receptor",""))),styles["small"]),Paragraph(escape(str(row.get("date",""))),styles["small"]),Paragraph(escape(str(row.get("reason",""))),styles["small"])])
        story.append(_styled_table(rows,[1.2*inch,3.1*inch,1.1*inch,4*inch]))
    else: story.append(Paragraph(labels["no_losses"],styles["body"]))
    story.append(Paragraph(labels["review_detail"],styles["section"])); reviewed=data.get("reviewed",[])
    if reviewed:
        rows=[[Paragraph(labels[k],styles["header"]) for k in ("quotation","customer","quoted","final_po","activity")]]
        for quote in reviewed:
            activity=[]
            for event in quote.get("events",[]):
                if event.get("event_type")=="review_saved": continue
                note=escape(str(event.get("note") or event.get("event_type") or "")); who=escape(str(event.get("user_name") or "")); activity.append(f"<b>{who}</b> {str(event.get('created_at',''))[11:16]}: {note}")
            rows.append([Paragraph(escape(str(quote.get("folio",""))),styles["small"]),Paragraph(escape(str(quote.get("receptor",""))),styles["small"]),Paragraph(_money(quote.get("total"),currency),styles["small"]),Paragraph(_money(quote.get("po_total"),currency) if quote.get("po_total") else "—",styles["small"]),Paragraph("<br/>".join(activity) or "—",styles["small"])])
        story.append(_styled_table(rows,[1.1*inch,2.2*inch,1.1*inch,1.1*inch,4*inch]))
    document.build(story,onFirstPage=_page,onLaterPages=_page); content=buffer.getvalue(); target.write_bytes(content); return content


def _styled_table(rows:list[list[Any]],widths:list[float])->Table:
    table=Table(rows,colWidths=widths,repeatRows=1); table.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),BLUE),("GRID",(0,0),(-1,-1),.35,LINE),("VALIGN",(0,0),(-1,-1),"TOP"),("ROWBACKGROUNDS",(0,1),(-1,-1),[colors.white,LIGHT]),("LEFTPADDING",(0,0),(-1,-1),5),("RIGHTPADDING",(0,0),(-1,-1),5),("TOPPADDING",(0,0),(-1,-1),5),("BOTTOMPADDING",(0,0),(-1,-1),5)])); return table


def build_report_xlsx(data: dict[str,Any], target: Path, language: str = "en") -> bytes:
    language=language if language in TEXT else "en"; labels=TEXT[language]; currency=data.get("currency","USD")
    workbook=Workbook(); summary=workbook.active; summary.title="Resumen" if language=="es" else "Summary"
    title=labels["special_title"] if data.get("workspace")=="special" else labels["title"]
    summary.append([title]); summary.append([labels["period"],data["start_date"],data["end_date"]]); summary.append([labels["generated_by"],data.get("generated_by","")]); summary.append([])
    summary.append([labels["summary"],labels["added"],labels["reviewed"],labels["status"],labels["po"]]); summary.append(["",data["new_quotes"],data["quotes_reviewed"],data["status_changes"],data["po_changes"]]); summary.append([])
    summary.append([labels["financial"],labels["pending"],labels["po_quoted"],labels["po_final"],labels["variance"]]); summary.append([currency,data["pending_value"],data["po_quoted_value"],data["po_value"],float(data["po_value"])-float(data["po_quoted_value"])])
    po=workbook.create_sheet("PO"); po.append([labels["quotation"],labels["customer"],labels["po_date"],labels["invoice_count"],labels["quoted"],labels["final_po"],labels["variance"]])
    for row in data.get("po_rows",[]): po.append([row.get("folio"),row.get("receptor"),row.get("po_date"),row.get("invoice_count",0),row.get("quoted_total"),row.get("po_total"),row.get("variance")])
    lost=workbook.create_sheet("Perdidas" if language=="es" else "Lost"); lost.append([labels["quotation"],labels["customer"],labels["date"],labels["reason"]])
    for row in data.get("lost_rows",[]): lost.append([row.get("folio"),row.get("receptor"),row.get("date"),row.get("reason")])
    reviewed=workbook.create_sheet("Revisadas" if language=="es" else "Reviewed"); reviewed.append([labels["quotation"],labels["customer"],labels["quoted"],labels["net"],labels["final_po"],labels["activity"]])
    for row in data.get("reviewed",[]):
        activity=" | ".join(f"{event.get('created_at','')} {event.get('user_name','')}: {event.get('note') or event.get('event_type','')}" for event in row.get("events",[]) if event.get("event_type")!="review_saved")
        reviewed.append([row.get("folio"),row.get("receptor"),row.get("total"),row.get("net_total"),row.get("po_total"),activity])
    for sheet in workbook.worksheets:
        sheet.freeze_panes="A2"; sheet.auto_filter.ref=sheet.dimensions
        for cell in sheet[1]: cell.font=Font(bold=True,color="FFFFFF"); cell.fill=PatternFill("solid",fgColor="0877C9"); cell.alignment=Alignment(vertical="center")
        for column in range(1,sheet.max_column+1):
            width=min(45,max(12,max(len(str(sheet.cell(row,column).value or "")) for row in range(1,min(sheet.max_row,100)+1))+2)); sheet.column_dimensions[get_column_letter(column)].width=width
        for row in sheet.iter_rows():
            for cell in row:
                if isinstance(cell.value,(int,float)) and cell.column in {2,3,4,5,6}: cell.number_format='¥#,##0' if currency=="JPY" else '$#,##0.00'
    target.parent.mkdir(parents=True,exist_ok=True); workbook.save(target); return target.read_bytes()


def build_daily_report_pdf(data: dict[str,Any], target: Path) -> bytes:
    if "start_date" not in data:
        data={**data,"start_date":data.get("date"),"end_date":data.get("date"),"currency":data.get("report_currency","USD"),
              "pending_value":data.get("pending_value",0),"loss_breakdown":data.get("loss_breakdown",{}),"po_rows":data.get("po_rows",[]),
              "lost_rows":data.get("lost_rows",[]),"reviewed":data.get("reviewed",data.get("quotes",[]))}
    return build_report_pdf(data,target,"en")
